version: '3'

services:

  app:
    image: handsomefencer/club:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./mise/env/production.env

  db:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./mise/env/production.env

volumes:
  db_data:
