version: '3'

services:

  app:
    image: handsomefencer/club:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./mise/env/production.env

  database:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./mise/env/production.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  db_data:
