#database: <%#= ENV['DATABASE_NAME'] %>
#username: <%#= ENV['DATABASE_USER'] %>
#password: <%#= ENV['DATABASE_PASSWORD'] %>
#port: <%#= ENV['DATABASE_PORT'] || '5432' %>
#host: <%#= ENV['DATABASE_HOST'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
