#database: <%#= ENV['DATABASE_NAME'] %>
#username: <%#= ENV['DATABASE_USER'] %>
#password: <%#= ENV['DATABASE_PASSWORD'] %>
#port: <%#= ENV['DATABASE_PORT'] || '5432' %>
#host: <%#= ENV['DATABASE_HOST'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
